### PR TITLE
Automatic rock-release PR: integrate rc-patches in master

### PR DESCRIPTION
**Pull request by goldhoorn**

### CODE REVIEW

**Comment by goldhoorn** [comment]
Autiproj is currently on master unable to do a bootstrap i would like to have the patches asap in master.

Furthermore as long autopro 2.0 is not finished i like to have the all packes option availible too.

**Comment by doudou** [comment]
Wouldn't the problems you have be fixed (in a much cleaner and generic way) by https://github.com/rock-core/autoproj/commit/1eca980542ada5043093935394b961e190e1777e ? It's currently only on stable.

**Comment by doudou** [comment]
See #74

**Comment by goldhoorn** [comment]
You patches seems to solve the issue. But can you please still add the all-known-packages option?

**Comment by doudou** [comment]
will do as soon as you update the PR

**Comment by doudou** [comment]
(to remote the rest)

**Comment by goldhoorn** [comment]
Can this be closed not since #75 is applied?

**Pull request closed without merging**
