### PR TITLE
fix configuration not being dirtied on modification to utilities

### PR DESCRIPTION
**Pull request by doudou**
The symptom was that `autoproj test enable ...` or
`autoproj test disable ...` would basically do nothing.

### CODE REVIEW

**Comment by g-arjones** [comment]
Good... I wonder when did this brake..

**Comment by doudou** [comment]
> I wonder when did this brake..

When I added the "save configuration only when modified" thingy. Actually, a good way to ensure it never happens again would be to `dup` the value returned by `get`. Thoughts ?

**Comment by g-arjones** [comment]
> would be to dup the value returned by get

That's better, IMO. We don't want anyone updating this hash without going through the API anyway...

**Comment by doudou** [comment]
Updated

**Comment by g-arjones** [comment]
Looks good... Live tested.

**Pull request merged**
