### PR TITLE
don't overwrie python shims during install

### LINKED ISSUE #357: [Question] How to automatically set up the default Python interpreter?
Recently, I've started receiving the following question during `autoproj update <package>` calls: 

> ''Select the path to the python executable [/usr/bin/python3]''

I've already tried the following `config.yml` for my bootstrap:

```yaml
USE_PYTHON: true
python_executable: /usr/bin/python2

#PYTHONPATH: /usr/bin/python2 (seems not effective)
```

With `USE_PYTHON` and `python_executable`, I can skip the question successfully. But the interpreter seems to be messed up (it points to .autoproj/bin/python), breaking my cmake packages build as it  cannot find a valid python interpreter:

> CMake Error at /usr/share/cmake-3.10/Modules/FindPythonInterp.cmake:116 (list):   list GET given empty list

I did notice some recent updates here, so I just would like to know the current proper way to set up (in a noninteractive way) the default python interpreter for my autoproj workspace.

### PR DESCRIPTION
**Pull request by g-arjones**
Fixes #357 

I had no idea autoproj would overwrite everything in `.autoproj/bin`.

### CODE REVIEW

**Comment by doudou** [comment]
I have to admit I forgot about it when I reviewed the PR that creates the stub.

A safer way would be to detect whether the binstub is a ruby script generated by bundler and ignore everything else. They all have a "This file was generated by Bundler" comment, and a she-bang line with `ruby` in it.

**Comment by doudou** [comment]
Possibly, just the she-bang line would be enough tbh. This is a controlled folder, anything ruby has been generated by bundler.

**Comment by g-arjones** [comment]
Done.

**Review by doudou — APPROVED** [review]

**Comment by caioaamaral** [comment]
Thanks for the fix! @g-arjones

**Pull request merged**
