### PR TITLE
Adding Ruby 2.2 and 2.3 definitions from master

### PR DESCRIPTION
**Pull request by planthaber**
to make stable work on ubuntu 16.04 (2.3 whould be sufficient)

### CODE REVIEW

**Comment by planthaber** [comment]
No idea why exactly rake fails, but whats the status on merging?

**Comment by doudou** [comment]
The problem is not merging, it's going to be the releasing

**Comment by planthaber** [comment]
Will this be released? Our buildserver still fails due to this issue

**Comment by planthaber** [comment]
@doudou Can you release this PR on rubygems? It keeps the buildserver from building rock-core on 16.04

**Comment by doudou** [comment]
It is already released since the 10th of June. [Version 1.13.5](https://rubygems.org/gems/autoproj/versions/1.13.5)

**Pull request merged**
