### PR TITLE
watch: workaround rb-inotify breaking when stopping within a callback

### PR DESCRIPTION
**Pull request by doudou**
See https://github.com/guard/rb-inotify/pull/93

### CODE REVIEW

**Comment by g-arjones** [comment]
Oh, hell.. :(

Shouldn't the thread be join()ed ?

**Comment by doudou** [comment]
> Shouldn't the thread be join()ed ?

I thought I could forgo that. I can also make it without a thread, if you think that it looks too ugly.

**Comment by g-arjones** [comment]
> I can also make it without a thread

How?

**Comment by doudou** [comment]
> How?

[`#run`](https://github.com/guard/rb-inotify/pull/93/files#diff-b45361f26e8f95687c1c484833b7122fR225) is basically a `while !stop` around `#process`. So, just reimplement the while loop and have our own stop flag.

**Comment by g-arjones** [comment]
Yeah.. I think I prefer the thread

**Comment by doudou** [comment]
So ... good to go ?

**Comment by g-arjones** [comment]
Yup :+1:

**Pull request merged**
