### PR TITLE
Cli test validation

### PR DESCRIPTION
**Pull request by g-arjones**

### CODE REVIEW

**Comment by doudou** [comment]
Could you maybe write a test ? That would be great.

**Comment by g-arjones** [comment]
Definitely, but there are no tests for the `test` subcommand so it will take a while..

**Comment by doudou** [comment]
> Definitely, but there are no tests for the `test` subcommand so it will take a while..

From my perspective, just add tests that check the specific regression you spotted. We can extend to cover the rest later.

There start to be quite a few examples in `test/cli/` to build from

**Comment by g-arjones** [comment]
Sounds good to me 👍

**Comment by g-arjones** [comment]
Here you go... Would you please release this along with the other changes currently in master (autobuild as well). Appreciate that...

**Comment by doudou** [comment]
> Would you please release this along with the other changes currently in master (autobuild as well). Appreciate that...

I'm trying to get the test suite to pass before I release everything. Have had little time to invest, unfortunately.

**Pull request merged**
