### PR TITLE
filter osdeps up-to-date packages during build

### LINKED ISSUE #340: Autoproj keeps trying to install python3-dev when a python_package is selected

### PR DESCRIPTION
**Pull request by g-arjones**
Fixes #340

### CODE REVIEW

**Comment by doudou** [comment]
It feels like a weird side-effect. Build already sets `checkout_only` to true, which definitely should not try to reinstall a package that's already there.

I rather think there's something wrong with the apt-dpkg detection of the package.

**Comment by g-arjones** [comment]
Not sure I get your point... `checkout_only` is not handled by `AptDpkgManager`. Autoproj always try to install internal dependencies during build, it's up to the manager to guess whether the dependency needs to be installed or not and `AptDpkgManager` only does that if either `filter_uptodate` or `install_only` are `true`.

**Comment by doudou** [comment]
`checkout_only` on `CLI::Update` should be translated into `install_only` for the osdeps

- https://github.com/rock-core/autoproj/blob/master/lib/autoproj/cli/update.rb#L105
- definition of `normalize_osdep_options`: https://github.com/rock-core/autoproj/blob/master/lib/autoproj/cli/update.rb#L185

I think that the problem is with the `install_only` logic of AptDpkgManager, which does not detect the package is already installed while `filter_uptodate_package` follows a different logic and does.

**Comment by g-arjones** [comment]
> checkout_only on CLI::Update should be translated into install_only for the osdeps

Yeah, that would make sense there's a bug somewhere in there. I've just printed `install_only` in `AptDpkgManager` and that is `false` there. I'll dig some more.

**Comment by g-arjones** [comment]
Found it... Good hint.

**Review by doudou — APPROVED** [review]

**Pull request merged**
